name: GPG Valifation

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a test key
        run: |
          gpg --batch --passphrase '' --quick-generate test
      - name: Import PGP keys and Testing
        run: |
          chmod +x init.sh
          ./init.sh
          gpg --list-key
          gpg --verify .github/workflows/test.txt.sig
