name: GPG Valifation

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a PGP key
        run: |
          chmod +x init.sh
          ./init.sh
          gpg --verify .github/workflows/test.txt.sig